-- Generated by Awesome Menu Generator
-- Based on LXMED http://lxmed.sourceforge.net/ project
module("applicationsmenu")

applicationsmenu = {}

applicationsmenu[10] = {
{[====[7-Zip FM]====], [====[7zFM]====]},
{[====[About Xfce]====], [====[xfce4-about]====]},
{[====[CopyQ]====], [====[copyq]====]},
{[====[File Manager]====], [====[exo-open --launch FileManager %u]====]},
{[====[Files]====], [====[nautilus --new-window]====]},
{[====[Gxmessage]====], [====[gxmessage]====]},
{[====[Help]====], [====[yelp %u]====]},
{[====[KeePassX]====], [====[keepassx %f]====]},
{[====[KeepassX v2]====], [====[/usr/bin/keepassx %f]====]},
{[====[Root Terminal]====], [====[gksu -l gnome-terminal]====]},
{[====[Terminal Emulator]====], [====[exo-open --launch TerminalEmulator]====]},
{[====[Xarchiver]====], [====[xarchiver]====]}
}
applicationsmenu[20] = {
}
applicationsmenu[30] = {
}
applicationsmenu[40] = {
{[====[Feh]====], [====[feh %f]====]},
{[====[FontForge]====], [====[fontforge]====]},
{[====[gThumb]====], [====[gthumb]====]},
{[====[Import with gThumb]====], [====[gthumb --import-photos]====]}
}
applicationsmenu[50] = {
{[====[Avahi SSH Server Browser]====], [====[/usr/bin/bssh]====]},
{[====[Avahi VNC Server Browser]====], [====[/usr/bin/bvnc]====]},
{[====[Chromium]====], [====[chromium]====]},
{[====[Dropbox]====], [====[dropboxd]====]},
{[====[Firefox]====], [====[/usr/lib/firefox/firefox %u]====]},
{[====[Mail Reader]====], [====[exo-open --launch MailReader %u]====]},
{[====[Skype]====], [====[skype]====]},
{[====[Start Transmission Minimized]====], [====[transmission-gtk --minimized]====]},
{[====[Web Browser]====], [====[exo-open --launch WebBrowser %u]====]},
{[====[Wicd]====], [====[/usr/bin/wicd-client]====]}
}
applicationsmenu[60] = {
{[====[Xpdf]====], [====[xpdf %f]====]}
}
applicationsmenu[70] = {
{[====[Connect to Server]====], [====[nautilus-connect-server]====]},
{[====[Desktop Icons]====], [====[nautilus --no-default-window --force-desktop]====]},
{[====[Notification Daemon]====], [====[/usr/lib/notification-daemon-1.0/notification-daemon]====]},
{[====[Run Software]====], [====[nautilus-autorun-software %u]====]},
{[====[sxiv]====], [====[sxiv %F]====]}
}
applicationsmenu[80] = {
{[====[CMake]====], [====[cmake-gui %f]====]},
{[====[Diffuse Merge Tool]====], [====[diffuse -s %F]====]},
{[====[New File]====], [====[subl3 --command new_file]====]},
{[====[OpenJDK Monitoring & Management Console]====], [====[/usr/bin/jconsole]====]},
{[====[OpenJDK Policy Tool]====], [====[/usr/bin/policytool]====]},
{[====[Qt Assistant]====], [====[/usr/lib/qt/bin/assistant]====]},
{[====[Qt Designer]====], [====[/usr/lib/qt/bin/designer]====]},
{[====[Qt Linguist]====], [====[/usr/lib/qt/bin/linguist]====]},
{[====[Qt QDbusViewer]====], [====[/usr/lib/qt/bin/qdbusviewer]====]},
{[====[Qt4 Assistant]====], [====[assistant-qt4]====]},
{[====[Qt4 Designer]====], [====[designer-qt4]====]},
{[====[Qt4 Linguist]====], [====[linguist-qt4]====]},
{[====[Qt4 QDbusViewer]====], [====[qdbusviewer-qt4]====]},
{[====[SmartGit/Hg]====], [====[smartgithg]====]}
}
applicationsmenu[90] = {
{[====[Cheese]====], [====[cheese]====]},
{[====[QT V4L2 test Utility]====], [====[qv4l2]====]}
}
applicationsmenu[100] = {
{[====[Avahi Zeroconf Browser]====], [====[/usr/bin/avahi-discover]====]},
{[====[Bulk Rename]====], [====[/usr/lib/Thunar/ThunarBulkRename %F]====]},
{[====[Cairo Composite Manager]====], [====[cairo-compmgr]====]},
{[====[dconf Editor]====], [====[dconf-editor]====]},
{[====[Open Folder with Thunar]====], [====[thunar %F]====]},
{[====[Oracle VM VirtualBox]====], [====[VirtualBox]====]},
{[====[System Log]====], [====[gnome-system-log]====]},
{[====[Thunar File Manager]====], [====[thunar %F]====]},
{[====[UNetbootin]====], [====[/usr/bin/unetbootin]====]},
{[====[urxvt]====], [====[urxvt]====]},
{[====[urxvt (client)]====], [====[urxvtc]====]},
{[====[urxvt (tabbed)]====], [====[urxvt-tabbed]====]},
{[====[UXTerm]====], [====[uxterm]====]},
{[====[XTerm]====], [====[xterm]====]},
{[====[Yaourt-Gui]====], [====[yaourt-gui]====]}
}
applicationsmenu[110] = {
{[====[Adobe Flash Player]====], [====[flash-player-properties]====]},
{[====[ARandR]====], [====[arandr]====]},
{[====[Customize Look and Feel]====], [====[lxappearance]====]},
{[====[File Manager]====], [====[thunar-settings]====]},
{[====[Monitor Settings]====], [====[lxrandr]====]},
{[====[Preferred Applications]====], [====[exo-preferred-applications]====]},
{[====[Privilege granting]====], [====[gksu-properties]====]},
{[====[Qt4 Config]====], [====[qtconfig-qt4]====]}
}

applicationsmenu[1] = {
{[====[Accessories]====], applicationsmenu[10]},
{[====[Education]====], applicationsmenu[20]},
{[====[Games]====], applicationsmenu[30]},
{[====[Graphics]====], applicationsmenu[40]},
{[====[Internet]====], applicationsmenu[50]},
{[====[Office]====], applicationsmenu[60]},
{[====[Other]====], applicationsmenu[70]},
{[====[Programming]====], applicationsmenu[80]},
{[====[Sound & Video]====], applicationsmenu[90]},
{[====[System Tools]====], applicationsmenu[100]},
{[====[Preferences]====], applicationsmenu[110]}
}

passed = applicationsmenu[1]
function applicationsmenu() return passed end